"""add tournament table and enums

Revision ID: ad02f82aafb2
Revises: 11c98c984481
Create Date: 2026-08-23 10:53:40.298847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad02f82aafb2'
down_revision = '11c98c984481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sport', sa.String(length=100), nullable=False),
    sa.Column('format', sa.Enum('ROUND_ROBIN', 'KNOCKOUT', name='tournament_format'), nullable=False),
    sa.Column('participant_type', sa.Enum('TEAM', 'INDIVIDUAL', name='participation_type'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REGISTRATION_OPEN', 'ONGOING', 'COMPLETED', name='tournament_status'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournaments')
    # ### end Alembic commands ###
