"""add participant, tournament_participant, match, match_participant, match_result, match_score, standing tables

Revision ID: c38af627e0ef
Revises: ad02f82aafb2
Create Date: 2026-08-23 15:44:49.220124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c38af627e0ef'
down_revision = 'ad02f82aafb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('round', sa.String(length=50), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', name='match_status'), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('TEAM', 'INDIVIDUAL', name='participant_entity_type'), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("(type = 'INDIVIDUAL' AND player_id IS NOT NULL AND team_id IS NULL) OR (type = 'TEAM' AND team_id IS NOT NULL AND player_id IS NULL)", name='ck_participant_exactly_one_of_player_or_team'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'participant_id', name='uq_match_participant')
    )
    op.create_table('match_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('winner_participant_id', sa.Integer(), nullable=True),
    sa.Column('result_type', sa.Enum('WIN', 'DRAW', name='result_type'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(result_type = 'WIN' AND winner_participant_id IS NOT NULL) OR (result_type = 'DRAW' AND winner_participant_id IS NULL)", name='ck_match_result_winner_consistency'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['winner_participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    op.create_table('standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('won', sa.Integer(), nullable=False),
    sa.Column('drawn', sa.Integer(), nullable=False),
    sa.Column('lost', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('score_difference', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.CheckConstraint('drawn >= 0', name='ck_standing_drawn_nonneg'),
    sa.CheckConstraint('lost >= 0', name='ck_standing_lost_nonneg'),
    sa.CheckConstraint('played >= 0', name='ck_standing_played_nonneg'),
    sa.CheckConstraint('points >= 0', name='ck_standing_points_nonneg'),
    sa.CheckConstraint('won >= 0', name='ck_standing_won_nonneg'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'participant_id', name='uq_tournament_standing')
    )
    op.create_table('tournament_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'participant_id', name='uq_tournament_participant')
    )
    op.create_table('match_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_participant_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['match_participant_id'], ['match_participants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_participant_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_scores')
    op.drop_table('tournament_participants')
    op.drop_table('standings')
    op.drop_table('match_results')
    op.drop_table('match_participants')
    op.drop_table('participants')
    op.drop_table('matches')
    # ### end Alembic commands ###
